// Code generated by protoc-gen-go. DO NOT EDIT.
// source: exampledata.proto

package exampleData

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TreeNodeExampleData struct {
	Id                   *int32   `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	Pid                  *int32   `protobuf:"varint,2,opt,name=Pid" json:"Pid,omitempty"`
	Extinfo              []byte   `protobuf:"bytes,3,opt,name=Extinfo" json:"Extinfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TreeNodeExampleData) Reset()         { *m = TreeNodeExampleData{} }
func (m *TreeNodeExampleData) String() string { return proto.CompactTextString(m) }
func (*TreeNodeExampleData) ProtoMessage()    {}
func (*TreeNodeExampleData) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae9b6a5dba7dcdae, []int{0}
}

func (m *TreeNodeExampleData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TreeNodeExampleData.Unmarshal(m, b)
}
func (m *TreeNodeExampleData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TreeNodeExampleData.Marshal(b, m, deterministic)
}
func (m *TreeNodeExampleData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TreeNodeExampleData.Merge(m, src)
}
func (m *TreeNodeExampleData) XXX_Size() int {
	return xxx_messageInfo_TreeNodeExampleData.Size(m)
}
func (m *TreeNodeExampleData) XXX_DiscardUnknown() {
	xxx_messageInfo_TreeNodeExampleData.DiscardUnknown(m)
}

var xxx_messageInfo_TreeNodeExampleData proto.InternalMessageInfo

func (m *TreeNodeExampleData) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *TreeNodeExampleData) GetPid() int32 {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return 0
}

func (m *TreeNodeExampleData) GetExtinfo() []byte {
	if m != nil {
		return m.Extinfo
	}
	return nil
}

func init() {
	proto.RegisterType((*TreeNodeExampleData)(nil), "exampleData.TreeNodeExampleData")
}

func init() { proto.RegisterFile("exampledata.proto", fileDescriptor_ae9b6a5dba7dcdae) }

var fileDescriptor_ae9b6a5dba7dcdae = []byte{
	// 114 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4c, 0xad, 0x48, 0xcc,
	0x2d, 0xc8, 0x49, 0x4d, 0x49, 0x2c, 0x49, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x86,
	0x0a, 0xb9, 0x24, 0x96, 0x24, 0x2a, 0x05, 0x72, 0x09, 0x87, 0x14, 0xa5, 0xa6, 0xfa, 0xe5, 0xa7,
	0xa4, 0xba, 0x22, 0x84, 0x85, 0xf8, 0xb8, 0x98, 0x3c, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x58,
	0x83, 0x98, 0x3c, 0x53, 0x84, 0x04, 0xb8, 0x98, 0x03, 0x32, 0x53, 0x24, 0x98, 0xc0, 0x02, 0x20,
	0xa6, 0x90, 0x04, 0x17, 0xbb, 0x6b, 0x45, 0x49, 0x66, 0x5e, 0x5a, 0xbe, 0x04, 0xb3, 0x02, 0xa3,
	0x06, 0x4f, 0x10, 0x8c, 0x0b, 0x08, 0x00, 0x00, 0xff, 0xff, 0xfa, 0x4c, 0x39, 0xa5, 0x73, 0x00,
	0x00, 0x00,
}
